// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addApplicationRole = `-- name: AddApplicationRole :exec
INSERT INTO app_role_access (application_id, role_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddApplicationRoleParams struct {
	ApplicationID uuid.UUID `json:"application_id"`
	RoleID        uuid.UUID `json:"role_id"`
}

func (q *Queries) AddApplicationRole(ctx context.Context, arg AddApplicationRoleParams) error {
	_, err := q.db.Exec(ctx, addApplicationRole, arg.ApplicationID, arg.RoleID)
	return err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (name, description, icon_url, access_type, target_host, target_port, is_active, is_public, sort_order, section_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, description, icon_url, access_type, target_host, target_port, is_active, is_public, sort_order, section_id, created_by, created_at, updated_at
`

type CreateApplicationParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IconUrl     pgtype.Text `json:"icon_url"`
	AccessType  string      `json:"access_type"`
	TargetHost  string      `json:"target_host"`
	TargetPort  pgtype.Int4 `json:"target_port"`
	IsActive    bool        `json:"is_active"`
	IsPublic    bool        `json:"is_public"`
	SortOrder   int32       `json:"sort_order"`
	SectionID   pgtype.UUID `json:"section_id"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.Name,
		arg.Description,
		arg.IconUrl,
		arg.AccessType,
		arg.TargetHost,
		arg.TargetPort,
		arg.IsActive,
		arg.IsPublic,
		arg.SortOrder,
		arg.SectionID,
		arg.CreatedBy,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.AccessType,
		&i.TargetHost,
		&i.TargetPort,
		&i.IsActive,
		&i.IsPublic,
		&i.SortOrder,
		&i.SectionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, name, description, icon_url, access_type, target_host, target_port, is_active, is_public, sort_order, section_id, created_by, created_at, updated_at FROM applications WHERE id = $1 LIMIT 1
`

func (q *Queries) GetApplicationByID(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.AccessType,
		&i.TargetHost,
		&i.TargetPort,
		&i.IsActive,
		&i.IsPublic,
		&i.SortOrder,
		&i.SectionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationRoles = `-- name: GetApplicationRoles :many
SELECT r.id, r.name, r.description, r.created_at FROM roles r
JOIN app_role_access ara ON ara.role_id = r.id
WHERE ara.application_id = $1
`

func (q *Queries) GetApplicationRoles(ctx context.Context, applicationID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, getApplicationRoles, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplications = `-- name: ListApplications :many
SELECT id, name, description, icon_url, access_type, target_host, target_port, is_active, is_public, sort_order, section_id, created_by, created_at, updated_at FROM applications ORDER BY sort_order, name
`

func (q *Queries) ListApplications(ctx context.Context) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IconUrl,
			&i.AccessType,
			&i.TargetHost,
			&i.TargetPort,
			&i.IsActive,
			&i.IsPublic,
			&i.SortOrder,
			&i.SectionID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsForRoles = `-- name: ListApplicationsForRoles :many
SELECT DISTINCT a.id, a.name, a.description, a.icon_url, a.access_type, a.target_host, a.target_port, a.is_active, a.is_public, a.sort_order, a.section_id, a.created_by, a.created_at, a.updated_at FROM applications a
JOIN app_role_access ara ON ara.application_id = a.id
JOIN roles r ON r.id = ara.role_id
WHERE r.name = ANY($1::text[]) AND a.is_active = TRUE
ORDER BY a.sort_order, a.name
`

func (q *Queries) ListApplicationsForRoles(ctx context.Context, dollar_1 []string) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsForRoles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IconUrl,
			&i.AccessType,
			&i.TargetHost,
			&i.TargetPort,
			&i.IsActive,
			&i.IsPublic,
			&i.SortOrder,
			&i.SectionID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicApplications = `-- name: ListPublicApplications :many
SELECT id, name, description, icon_url, access_type, target_host, target_port, is_active, is_public, sort_order, section_id, created_by, created_at, updated_at FROM applications
WHERE is_active = TRUE AND is_public = TRUE
ORDER BY sort_order, name
`

func (q *Queries) ListPublicApplications(ctx context.Context) ([]Application, error) {
	rows, err := q.db.Query(ctx, listPublicApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Application{}
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IconUrl,
			&i.AccessType,
			&i.TargetHost,
			&i.TargetPort,
			&i.IsActive,
			&i.IsPublic,
			&i.SortOrder,
			&i.SectionID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setApplicationRoles = `-- name: SetApplicationRoles :exec
DELETE FROM app_role_access WHERE application_id = $1
`

func (q *Queries) SetApplicationRoles(ctx context.Context, applicationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setApplicationRoles, applicationID)
	return err
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications SET
    name = $2, description = $3, icon_url = $4, access_type = $5,
    target_host = $6, target_port = $7, is_active = $8, is_public = $9, sort_order = $10,
    section_id = $11,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, icon_url, access_type, target_host, target_port, is_active, is_public, sort_order, section_id, created_by, created_at, updated_at
`

type UpdateApplicationParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IconUrl     pgtype.Text `json:"icon_url"`
	AccessType  string      `json:"access_type"`
	TargetHost  string      `json:"target_host"`
	TargetPort  pgtype.Int4 `json:"target_port"`
	IsActive    bool        `json:"is_active"`
	IsPublic    bool        `json:"is_public"`
	SortOrder   int32       `json:"sort_order"`
	SectionID   pgtype.UUID `json:"section_id"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IconUrl,
		arg.AccessType,
		arg.TargetHost,
		arg.TargetPort,
		arg.IsActive,
		arg.IsPublic,
		arg.SortOrder,
		arg.SectionID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IconUrl,
		&i.AccessType,
		&i.TargetHost,
		&i.TargetPort,
		&i.IsActive,
		&i.IsPublic,
		&i.SortOrder,
		&i.SectionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
