// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
WHERE ($1::text IS NULL OR $1 = '' OR action = $1)
  AND ($2::text IS NULL OR $2 = '' OR resource_type = $2)
`

type CountAuditLogsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (actor_id, actor_username, action, resource_type, resource_id, details, ip_address)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, actor_id, actor_username, action, resource_type, resource_id, details, ip_address, created_at
`

type CreateAuditLogParams struct {
	ActorID       pgtype.UUID `json:"actor_id"`
	ActorUsername pgtype.Text `json:"actor_username"`
	Action        string      `json:"action"`
	ResourceType  pgtype.Text `json:"resource_type"`
	ResourceID    pgtype.Text `json:"resource_id"`
	Details       []byte      `json:"details"`
	IpAddress     pgtype.Text `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorID,
		arg.ActorUsername,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Details,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.ActorUsername,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Details,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_id, actor_username, action, resource_type, resource_id, details, ip_address, created_at FROM audit_logs
WHERE ($1::text IS NULL OR $1 = '' OR action = $1)
  AND ($2::text IS NULL OR $2 = '' OR resource_type = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAuditLogsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorUsername,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
