// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_sections.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCatalogSection = `-- name: CreateCatalogSection :one
INSERT INTO catalog_sections (name, sort_order)
VALUES ($1, $2)
RETURNING id, name, sort_order, created_at
`

type CreateCatalogSectionParams struct {
	Name      string `json:"name"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) CreateCatalogSection(ctx context.Context, arg CreateCatalogSectionParams) (CatalogSection, error) {
	row := q.db.QueryRow(ctx, createCatalogSection, arg.Name, arg.SortOrder)
	var i CatalogSection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCatalogSection = `-- name: DeleteCatalogSection :exec
DELETE FROM catalog_sections WHERE id = $1
`

func (q *Queries) DeleteCatalogSection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCatalogSection, id)
	return err
}

const getCatalogSectionByID = `-- name: GetCatalogSectionByID :one
SELECT id, name, sort_order, created_at FROM catalog_sections WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCatalogSectionByID(ctx context.Context, id uuid.UUID) (CatalogSection, error) {
	row := q.db.QueryRow(ctx, getCatalogSectionByID, id)
	var i CatalogSection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listCatalogSections = `-- name: ListCatalogSections :many
SELECT id, name, sort_order, created_at FROM catalog_sections ORDER BY sort_order, name
`

func (q *Queries) ListCatalogSections(ctx context.Context) ([]CatalogSection, error) {
	rows, err := q.db.Query(ctx, listCatalogSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CatalogSection{}
	for rows.Next() {
		var i CatalogSection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCatalogSection = `-- name: UpdateCatalogSection :one
UPDATE catalog_sections SET
    name = $2,
    sort_order = $3
WHERE id = $1
RETURNING id, name, sort_order, created_at
`

type UpdateCatalogSectionParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdateCatalogSection(ctx context.Context, arg UpdateCatalogSectionParams) (CatalogSection, error) {
	row := q.db.QueryRow(ctx, updateCatalogSection, arg.ID, arg.Name, arg.SortOrder)
	var i CatalogSection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
