// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cve_findings.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCVEFindings = `-- name: CountCVEFindings :one
SELECT COUNT(*) FROM cve_findings
`

func (q *Queries) CountCVEFindings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCVEFindings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCVEFindingsFiltered = `-- name: CountCVEFindingsFiltered :one
SELECT COUNT(*) FROM cve_findings
WHERE ($1 = '' OR severity::text = $1)
  AND ($2 = '' OR image_name ILIKE '%' || $2 || '%' OR cve_id ILIKE '%' || $2 || '%')
`

type CountCVEFindingsFilteredParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CountCVEFindingsFiltered(ctx context.Context, arg CountCVEFindingsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCVEFindingsFiltered, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldCVEFindings = `-- name: DeleteOldCVEFindings :exec
DELETE FROM cve_findings WHERE created_at < $1
`

func (q *Queries) DeleteOldCVEFindings(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldCVEFindings, createdAt)
	return err
}

const getCVESummary = `-- name: GetCVESummary :one
SELECT
    COUNT(*) FILTER (WHERE severity = 'critical') AS critical_count,
    COUNT(*) FILTER (WHERE severity = 'high') AS high_count,
    COUNT(*) FILTER (WHERE severity = 'medium') AS medium_count,
    COUNT(*) FILTER (WHERE severity = 'low') AS low_count
FROM cve_findings
`

type GetCVESummaryRow struct {
	CriticalCount int64 `json:"critical_count"`
	HighCount     int64 `json:"high_count"`
	MediumCount   int64 `json:"medium_count"`
	LowCount      int64 `json:"low_count"`
}

func (q *Queries) GetCVESummary(ctx context.Context) (GetCVESummaryRow, error) {
	row := q.db.QueryRow(ctx, getCVESummary)
	var i GetCVESummaryRow
	err := row.Scan(
		&i.CriticalCount,
		&i.HighCount,
		&i.MediumCount,
		&i.LowCount,
	)
	return i, err
}

const getCVESummaryFiltered = `-- name: GetCVESummaryFiltered :one
SELECT
    COUNT(*) FILTER (WHERE severity = 'critical') AS critical_count,
    COUNT(*) FILTER (WHERE severity = 'high') AS high_count,
    COUNT(*) FILTER (WHERE severity = 'medium') AS medium_count,
    COUNT(*) FILTER (WHERE severity = 'low') AS low_count
FROM cve_findings
WHERE ($1 = '' OR severity::text = $1)
  AND ($2 = '' OR image_name ILIKE '%' || $2 || '%' OR cve_id ILIKE '%' || $2 || '%')
`

type GetCVESummaryFilteredParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

type GetCVESummaryFilteredRow struct {
	CriticalCount int64 `json:"critical_count"`
	HighCount     int64 `json:"high_count"`
	MediumCount   int64 `json:"medium_count"`
	LowCount      int64 `json:"low_count"`
}

func (q *Queries) GetCVESummaryFiltered(ctx context.Context, arg GetCVESummaryFilteredParams) (GetCVESummaryFilteredRow, error) {
	row := q.db.QueryRow(ctx, getCVESummaryFiltered, arg.Column1, arg.Column2)
	var i GetCVESummaryFilteredRow
	err := row.Scan(
		&i.CriticalCount,
		&i.HighCount,
		&i.MediumCount,
		&i.LowCount,
	)
	return i, err
}

const listCVEFindings = `-- name: ListCVEFindings :many
SELECT id, image_name, image_tag, cve_id, severity, package_name, installed_version, fixed_version, source, scan_date, raw_payload, created_at FROM cve_findings ORDER BY scan_date DESC, severity LIMIT $1 OFFSET $2
`

type ListCVEFindingsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCVEFindings(ctx context.Context, arg ListCVEFindingsParams) ([]CveFinding, error) {
	rows, err := q.db.Query(ctx, listCVEFindings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CveFinding{}
	for rows.Next() {
		var i CveFinding
		if err := rows.Scan(
			&i.ID,
			&i.ImageName,
			&i.ImageTag,
			&i.CveID,
			&i.Severity,
			&i.PackageName,
			&i.InstalledVersion,
			&i.FixedVersion,
			&i.Source,
			&i.ScanDate,
			&i.RawPayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCVEFindingsBySeverity = `-- name: ListCVEFindingsBySeverity :many
SELECT id, image_name, image_tag, cve_id, severity, package_name, installed_version, fixed_version, source, scan_date, raw_payload, created_at FROM cve_findings WHERE severity = $1 ORDER BY scan_date DESC LIMIT $2 OFFSET $3
`

type ListCVEFindingsBySeverityParams struct {
	Severity string `json:"severity"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListCVEFindingsBySeverity(ctx context.Context, arg ListCVEFindingsBySeverityParams) ([]CveFinding, error) {
	rows, err := q.db.Query(ctx, listCVEFindingsBySeverity, arg.Severity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CveFinding{}
	for rows.Next() {
		var i CveFinding
		if err := rows.Scan(
			&i.ID,
			&i.ImageName,
			&i.ImageTag,
			&i.CveID,
			&i.Severity,
			&i.PackageName,
			&i.InstalledVersion,
			&i.FixedVersion,
			&i.Source,
			&i.ScanDate,
			&i.RawPayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCVEFindingsFiltered = `-- name: ListCVEFindingsFiltered :many
SELECT id, image_name, image_tag, cve_id, severity, package_name, installed_version, fixed_version, source, scan_date, raw_payload, created_at FROM cve_findings
WHERE ($1 = '' OR severity::text = $1)
  AND ($2 = '' OR image_name ILIKE '%' || $2 || '%' OR cve_id ILIKE '%' || $2 || '%')
ORDER BY scan_date DESC, severity
LIMIT $3 OFFSET $4
`

type ListCVEFindingsFilteredParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListCVEFindingsFiltered(ctx context.Context, arg ListCVEFindingsFilteredParams) ([]CveFinding, error) {
	rows, err := q.db.Query(ctx, listCVEFindingsFiltered,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CveFinding{}
	for rows.Next() {
		var i CveFinding
		if err := rows.Scan(
			&i.ID,
			&i.ImageName,
			&i.ImageTag,
			&i.CveID,
			&i.Severity,
			&i.PackageName,
			&i.InstalledVersion,
			&i.FixedVersion,
			&i.Source,
			&i.ScanDate,
			&i.RawPayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCVEFinding = `-- name: UpsertCVEFinding :one
INSERT INTO cve_findings (image_name, image_tag, cve_id, severity, package_name, installed_version, fixed_version, source, scan_date, raw_payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (image_name, image_tag, cve_id, source) DO UPDATE SET
    severity = EXCLUDED.severity,
    package_name = EXCLUDED.package_name,
    installed_version = EXCLUDED.installed_version,
    fixed_version = EXCLUDED.fixed_version,
    scan_date = EXCLUDED.scan_date,
    raw_payload = EXCLUDED.raw_payload
RETURNING id, image_name, image_tag, cve_id, severity, package_name, installed_version, fixed_version, source, scan_date, raw_payload, created_at
`

type UpsertCVEFindingParams struct {
	ImageName        string      `json:"image_name"`
	ImageTag         string      `json:"image_tag"`
	CveID            string      `json:"cve_id"`
	Severity         string      `json:"severity"`
	PackageName      pgtype.Text `json:"package_name"`
	InstalledVersion pgtype.Text `json:"installed_version"`
	FixedVersion     pgtype.Text `json:"fixed_version"`
	Source           string      `json:"source"`
	ScanDate         time.Time   `json:"scan_date"`
	RawPayload       []byte      `json:"raw_payload"`
}

func (q *Queries) UpsertCVEFinding(ctx context.Context, arg UpsertCVEFindingParams) (CveFinding, error) {
	row := q.db.QueryRow(ctx, upsertCVEFinding,
		arg.ImageName,
		arg.ImageTag,
		arg.CveID,
		arg.Severity,
		arg.PackageName,
		arg.InstalledVersion,
		arg.FixedVersion,
		arg.Source,
		arg.ScanDate,
		arg.RawPayload,
	)
	var i CveFinding
	err := row.Scan(
		&i.ID,
		&i.ImageName,
		&i.ImageTag,
		&i.CveID,
		&i.Severity,
		&i.PackageName,
		&i.InstalledVersion,
		&i.FixedVersion,
		&i.Source,
		&i.ScanDate,
		&i.RawPayload,
		&i.CreatedAt,
	)
	return i, err
}
