// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployment_reports.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDeploymentReports = `-- name: CountDeploymentReports :one
SELECT COUNT(*) FROM deployment_reports
`

func (q *Queries) CountDeploymentReports(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDeploymentReports)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeploymentReportsFiltered = `-- name: CountDeploymentReportsFiltered :one
SELECT COUNT(*) FROM deployment_reports
WHERE ($1 = '' OR app_name ILIKE '%' || $1 || '%' OR image_name ILIKE '%' || $1 || '%')
  AND ($2 = '' OR status::text = $2)
`

type CountDeploymentReportsFilteredParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CountDeploymentReportsFiltered(ctx context.Context, arg CountDeploymentReportsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDeploymentReportsFiltered, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeploymentReport = `-- name: CreateDeploymentReport :one
INSERT INTO deployment_reports (app_name, image_name, image_tag, triggered_by, status, critical_count, high_count, medium_count, low_count, report_url, raw_payload, payload_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, app_name, image_name, image_tag, triggered_by, status, critical_count, high_count, medium_count, low_count, report_url, raw_payload, payload_hash, received_at
`

type CreateDeploymentReportParams struct {
	AppName       string      `json:"app_name"`
	ImageName     string      `json:"image_name"`
	ImageTag      string      `json:"image_tag"`
	TriggeredBy   pgtype.Text `json:"triggered_by"`
	Status        string      `json:"status"`
	CriticalCount int32       `json:"critical_count"`
	HighCount     int32       `json:"high_count"`
	MediumCount   int32       `json:"medium_count"`
	LowCount      int32       `json:"low_count"`
	ReportUrl     pgtype.Text `json:"report_url"`
	RawPayload    []byte      `json:"raw_payload"`
	PayloadHash   pgtype.Text `json:"payload_hash"`
}

func (q *Queries) CreateDeploymentReport(ctx context.Context, arg CreateDeploymentReportParams) (DeploymentReport, error) {
	row := q.db.QueryRow(ctx, createDeploymentReport,
		arg.AppName,
		arg.ImageName,
		arg.ImageTag,
		arg.TriggeredBy,
		arg.Status,
		arg.CriticalCount,
		arg.HighCount,
		arg.MediumCount,
		arg.LowCount,
		arg.ReportUrl,
		arg.RawPayload,
		arg.PayloadHash,
	)
	var i DeploymentReport
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.ImageName,
		&i.ImageTag,
		&i.TriggeredBy,
		&i.Status,
		&i.CriticalCount,
		&i.HighCount,
		&i.MediumCount,
		&i.LowCount,
		&i.ReportUrl,
		&i.RawPayload,
		&i.PayloadHash,
		&i.ReceivedAt,
	)
	return i, err
}

const deleteOldDeploymentReports = `-- name: DeleteOldDeploymentReports :exec
DELETE FROM deployment_reports WHERE received_at < $1
`

func (q *Queries) DeleteOldDeploymentReports(ctx context.Context, receivedAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldDeploymentReports, receivedAt)
	return err
}

const getDeploymentReportByID = `-- name: GetDeploymentReportByID :one
SELECT id, app_name, image_name, image_tag, triggered_by, status, critical_count, high_count, medium_count, low_count, report_url, raw_payload, payload_hash, received_at FROM deployment_reports WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDeploymentReportByID(ctx context.Context, id uuid.UUID) (DeploymentReport, error) {
	row := q.db.QueryRow(ctx, getDeploymentReportByID, id)
	var i DeploymentReport
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.ImageName,
		&i.ImageTag,
		&i.TriggeredBy,
		&i.Status,
		&i.CriticalCount,
		&i.HighCount,
		&i.MediumCount,
		&i.LowCount,
		&i.ReportUrl,
		&i.RawPayload,
		&i.PayloadHash,
		&i.ReceivedAt,
	)
	return i, err
}

const getDeploymentReportByPayloadHash = `-- name: GetDeploymentReportByPayloadHash :one
SELECT id, app_name, image_name, image_tag, triggered_by, status, critical_count, high_count, medium_count, low_count, report_url, raw_payload, payload_hash, received_at FROM deployment_reports WHERE payload_hash = $1 LIMIT 1
`

func (q *Queries) GetDeploymentReportByPayloadHash(ctx context.Context, payloadHash pgtype.Text) (DeploymentReport, error) {
	row := q.db.QueryRow(ctx, getDeploymentReportByPayloadHash, payloadHash)
	var i DeploymentReport
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.ImageName,
		&i.ImageTag,
		&i.TriggeredBy,
		&i.Status,
		&i.CriticalCount,
		&i.HighCount,
		&i.MediumCount,
		&i.LowCount,
		&i.ReportUrl,
		&i.RawPayload,
		&i.PayloadHash,
		&i.ReceivedAt,
	)
	return i, err
}

const listDeploymentReports = `-- name: ListDeploymentReports :many
SELECT id, app_name, image_name, image_tag, triggered_by, status, critical_count, high_count, medium_count, low_count, report_url, raw_payload, payload_hash, received_at FROM deployment_reports ORDER BY received_at DESC LIMIT $1 OFFSET $2
`

type ListDeploymentReportsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDeploymentReports(ctx context.Context, arg ListDeploymentReportsParams) ([]DeploymentReport, error) {
	rows, err := q.db.Query(ctx, listDeploymentReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentReport{}
	for rows.Next() {
		var i DeploymentReport
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.ImageName,
			&i.ImageTag,
			&i.TriggeredBy,
			&i.Status,
			&i.CriticalCount,
			&i.HighCount,
			&i.MediumCount,
			&i.LowCount,
			&i.ReportUrl,
			&i.RawPayload,
			&i.PayloadHash,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentReportsFiltered = `-- name: ListDeploymentReportsFiltered :many
SELECT id, app_name, image_name, image_tag, triggered_by, status, critical_count, high_count, medium_count, low_count, report_url, raw_payload, payload_hash, received_at FROM deployment_reports
WHERE ($1 = '' OR app_name ILIKE '%' || $1 || '%' OR image_name ILIKE '%' || $1 || '%')
  AND ($2 = '' OR status::text = $2)
ORDER BY received_at DESC
LIMIT $3 OFFSET $4
`

type ListDeploymentReportsFilteredParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListDeploymentReportsFiltered(ctx context.Context, arg ListDeploymentReportsFilteredParams) ([]DeploymentReport, error) {
	rows, err := q.db.Query(ctx, listDeploymentReportsFiltered,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentReport{}
	for rows.Next() {
		var i DeploymentReport
		if err := rows.Scan(
			&i.ID,
			&i.AppName,
			&i.ImageName,
			&i.ImageTag,
			&i.TriggeredBy,
			&i.Status,
			&i.CriticalCount,
			&i.HighCount,
			&i.MediumCount,
			&i.LowCount,
			&i.ReportUrl,
			&i.RawPayload,
			&i.PayloadHash,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
