// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_outbound.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEmailOutboundLog = `-- name: CountEmailOutboundLog :one
SELECT COUNT(*) FROM email_outbound_log
WHERE ($1 = '' OR event_type = $1)
`

func (q *Queries) CountEmailOutboundLog(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countEmailOutboundLog, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailOutboundLog = `-- name: CreateEmailOutboundLog :one
INSERT INTO email_outbound_log (event_type, subject, body_preview, status, error_message, triggered_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_type, subject, body_preview, status, error_message, triggered_by, created_at
`

type CreateEmailOutboundLogParams struct {
	EventType    string      `json:"event_type"`
	Subject      string      `json:"subject"`
	BodyPreview  string      `json:"body_preview"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	TriggeredBy  pgtype.UUID `json:"triggered_by"`
}

func (q *Queries) CreateEmailOutboundLog(ctx context.Context, arg CreateEmailOutboundLogParams) (EmailOutboundLog, error) {
	row := q.db.QueryRow(ctx, createEmailOutboundLog,
		arg.EventType,
		arg.Subject,
		arg.BodyPreview,
		arg.Status,
		arg.ErrorMessage,
		arg.TriggeredBy,
	)
	var i EmailOutboundLog
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Subject,
		&i.BodyPreview,
		&i.Status,
		&i.ErrorMessage,
		&i.TriggeredBy,
		&i.CreatedAt,
	)
	return i, err
}

const createEmailOutboundRecipient = `-- name: CreateEmailOutboundRecipient :one
INSERT INTO email_outbound_recipients (log_id, email, user_id, status, error_message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, log_id, email, user_id, status, error_message
`

type CreateEmailOutboundRecipientParams struct {
	LogID        uuid.UUID   `json:"log_id"`
	Email        string      `json:"email"`
	UserID       pgtype.UUID `json:"user_id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) CreateEmailOutboundRecipient(ctx context.Context, arg CreateEmailOutboundRecipientParams) (EmailOutboundRecipient, error) {
	row := q.db.QueryRow(ctx, createEmailOutboundRecipient,
		arg.LogID,
		arg.Email,
		arg.UserID,
		arg.Status,
		arg.ErrorMessage,
	)
	var i EmailOutboundRecipient
	err := row.Scan(
		&i.ID,
		&i.LogID,
		&i.Email,
		&i.UserID,
		&i.Status,
		&i.ErrorMessage,
	)
	return i, err
}

const getEmailOutboundLogByID = `-- name: GetEmailOutboundLogByID :one
SELECT id, event_type, subject, body_preview, status, error_message, triggered_by, created_at FROM email_outbound_log WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmailOutboundLogByID(ctx context.Context, id uuid.UUID) (EmailOutboundLog, error) {
	row := q.db.QueryRow(ctx, getEmailOutboundLogByID, id)
	var i EmailOutboundLog
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Subject,
		&i.BodyPreview,
		&i.Status,
		&i.ErrorMessage,
		&i.TriggeredBy,
		&i.CreatedAt,
	)
	return i, err
}

const listEmailOutboundLog = `-- name: ListEmailOutboundLog :many
SELECT id, event_type, subject, body_preview, status, error_message, triggered_by, created_at FROM email_outbound_log
WHERE ($1 = '' OR event_type = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEmailOutboundLogParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListEmailOutboundLog(ctx context.Context, arg ListEmailOutboundLogParams) ([]EmailOutboundLog, error) {
	rows, err := q.db.Query(ctx, listEmailOutboundLog, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailOutboundLog{}
	for rows.Next() {
		var i EmailOutboundLog
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Subject,
			&i.BodyPreview,
			&i.Status,
			&i.ErrorMessage,
			&i.TriggeredBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailOutboundRecipientsByLogIDs = `-- name: ListEmailOutboundRecipientsByLogIDs :many
SELECT id, log_id, email, user_id, status, error_message FROM email_outbound_recipients
WHERE log_id = ANY($1::uuid[])
ORDER BY email
`

func (q *Queries) ListEmailOutboundRecipientsByLogIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]EmailOutboundRecipient, error) {
	rows, err := q.db.Query(ctx, listEmailOutboundRecipientsByLogIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailOutboundRecipient{}
	for rows.Next() {
		var i EmailOutboundRecipient
		if err := rows.Scan(
			&i.ID,
			&i.LogID,
			&i.Email,
			&i.UserID,
			&i.Status,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
