// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO user_invitations (email, username, display_name, role_ids, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, username, display_name, role_ids, token_hash, invited_by, expires_at, accepted_at, created_at
`

type CreateInvitationParams struct {
	Email       string      `json:"email"`
	Username    string      `json:"username"`
	DisplayName pgtype.Text `json:"display_name"`
	RoleIds     []uuid.UUID `json:"role_ids"`
	TokenHash   string      `json:"token_hash"`
	InvitedBy   pgtype.UUID `json:"invited_by"`
	ExpiresAt   time.Time   `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.RoleIds,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.RoleIds,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, email, username, display_name, role_ids, token_hash, invited_by, expires_at, accepted_at, created_at FROM user_invitations
WHERE token_hash = $1 AND accepted_at IS NULL AND expires_at > now()
LIMIT 1
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.RoleIds,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingInvitationByEmail = `-- name: GetPendingInvitationByEmail :one
SELECT id, email, username, display_name, role_ids, token_hash, invited_by, expires_at, accepted_at, created_at FROM user_invitations
WHERE lower(email) = lower($1) AND accepted_at IS NULL AND expires_at > now()
LIMIT 1
`

func (q *Queries) GetPendingInvitationByEmail(ctx context.Context, lower string) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, getPendingInvitationByEmail, lower)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.RoleIds,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingInvitationByUsername = `-- name: GetPendingInvitationByUsername :one
SELECT id, email, username, display_name, role_ids, token_hash, invited_by, expires_at, accepted_at, created_at FROM user_invitations
WHERE lower(username) = lower($1) AND accepted_at IS NULL AND expires_at > now()
LIMIT 1
`

func (q *Queries) GetPendingInvitationByUsername(ctx context.Context, lower string) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, getPendingInvitationByUsername, lower)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.RoleIds,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingInvitations = `-- name: ListPendingInvitations :many
SELECT id, email, username, display_name, role_ids, token_hash, invited_by, expires_at, accepted_at, created_at FROM user_invitations
WHERE accepted_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitations(ctx context.Context) ([]UserInvitation, error) {
	rows, err := q.db.Query(ctx, listPendingInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserInvitation{}
	for rows.Next() {
		var i UserInvitation
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.DisplayName,
			&i.RoleIds,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationAccepted = `-- name: MarkInvitationAccepted :exec
UPDATE user_invitations SET accepted_at = now() WHERE id = $1
`

func (q *Queries) MarkInvitationAccepted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInvitationAccepted, id)
	return err
}
