// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessType string

const (
	AccessTypeIpPort AccessType = "ip_port"
	AccessTypeUrl    AccessType = "url"
)

func (e *AccessType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccessType(s)
	case string:
		*e = AccessType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccessType: %T", src)
	}
	return nil
}

type NullAccessType struct {
	AccessType AccessType `json:"access_type"`
	Valid      bool       `json:"valid"` // Valid is true if AccessType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccessType) Scan(value interface{}) error {
	if value == nil {
		ns.AccessType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccessType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccessType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccessType), nil
}

type AuthType string

const (
	AuthTypeLocal AuthType = "local"
	AuthTypeOidc  AuthType = "oidc"
)

func (e *AuthType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthType(s)
	case string:
		*e = AuthType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthType: %T", src)
	}
	return nil
}

type NullAuthType struct {
	AuthType AuthType `json:"auth_type"`
	Valid    bool     `json:"valid"` // Valid is true if AuthType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthType), nil
}

type CveSeverity string

const (
	CveSeverityCritical CveSeverity = "critical"
	CveSeverityHigh     CveSeverity = "high"
	CveSeverityMedium   CveSeverity = "medium"
	CveSeverityLow      CveSeverity = "low"
	CveSeverityUnknown  CveSeverity = "unknown"
)

func (e *CveSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CveSeverity(s)
	case string:
		*e = CveSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for CveSeverity: %T", src)
	}
	return nil
}

type NullCveSeverity struct {
	CveSeverity CveSeverity `json:"cve_severity"`
	Valid       bool        `json:"valid"` // Valid is true if CveSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCveSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.CveSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CveSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCveSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CveSeverity), nil
}

type DeployStatus string

const (
	DeployStatusSuccess DeployStatus = "success"
	DeployStatusFailed  DeployStatus = "failed"
	DeployStatusPartial DeployStatus = "partial"
)

func (e *DeployStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeployStatus(s)
	case string:
		*e = DeployStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeployStatus: %T", src)
	}
	return nil
}

type NullDeployStatus struct {
	DeployStatus DeployStatus `json:"deploy_status"`
	Valid        bool         `json:"valid"` // Valid is true if DeployStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeployStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeployStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeployStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeployStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeployStatus), nil
}

type FindingSource string

const (
	FindingSourceWeeklyPull FindingSource = "weekly_pull"
	FindingSourceWebhook    FindingSource = "webhook"
)

func (e *FindingSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FindingSource(s)
	case string:
		*e = FindingSource(s)
	default:
		return fmt.Errorf("unsupported scan type for FindingSource: %T", src)
	}
	return nil
}

type NullFindingSource struct {
	FindingSource FindingSource `json:"finding_source"`
	Valid         bool          `json:"valid"` // Valid is true if FindingSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFindingSource) Scan(value interface{}) error {
	if value == nil {
		ns.FindingSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FindingSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFindingSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FindingSource), nil
}

type NotificationChannel string

const (
	NotificationChannelEmail NotificationChannel = "email"
	NotificationChannelTeams NotificationChannel = "teams"
	NotificationChannelInApp NotificationChannel = "in_app"
)

func (e *NotificationChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationChannel(s)
	case string:
		*e = NotificationChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationChannel: %T", src)
	}
	return nil
}

type NullNotificationChannel struct {
	NotificationChannel NotificationChannel `json:"notification_channel"`
	Valid               bool                `json:"valid"` // Valid is true if NotificationChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationChannel) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationChannel), nil
}

type NotificationEventType string

const (
	NotificationEventTypeWeeklyDigest     NotificationEventType = "weekly_digest"
	NotificationEventTypeDeploymentReport NotificationEventType = "deployment_report"
	NotificationEventTypeCriticalCve      NotificationEventType = "critical_cve"
)

func (e *NotificationEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationEventType(s)
	case string:
		*e = NotificationEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationEventType: %T", src)
	}
	return nil
}

type NullNotificationEventType struct {
	NotificationEventType NotificationEventType `json:"notification_event_type"`
	Valid                 bool                  `json:"valid"` // Valid is true if NotificationEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationEventType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationEventType), nil
}

type NotificationSeverity string

const (
	NotificationSeverityInfo     NotificationSeverity = "info"
	NotificationSeverityWarning  NotificationSeverity = "warning"
	NotificationSeverityCritical NotificationSeverity = "critical"
)

func (e *NotificationSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationSeverity(s)
	case string:
		*e = NotificationSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationSeverity: %T", src)
	}
	return nil
}

type NullNotificationSeverity struct {
	NotificationSeverity NotificationSeverity `json:"notification_severity"`
	Valid                bool                 `json:"valid"` // Valid is true if NotificationSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationSeverity), nil
}

type WebhookEventStatus string

const (
	WebhookEventStatusAccepted  WebhookEventStatus = "accepted"
	WebhookEventStatusProcessed WebhookEventStatus = "processed"
	WebhookEventStatusFailed    WebhookEventStatus = "failed"
)

func (e *WebhookEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookEventStatus(s)
	case string:
		*e = WebhookEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookEventStatus: %T", src)
	}
	return nil
}

type NullWebhookEventStatus struct {
	WebhookEventStatus WebhookEventStatus `json:"webhook_event_status"`
	Valid              bool               `json:"valid"` // Valid is true if WebhookEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookEventStatus), nil
}

type WebhookSource string

const (
	WebhookSourceHarbor WebhookSource = "harbor"
	WebhookSourceTrivy  WebhookSource = "trivy"
)

func (e *WebhookSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookSource(s)
	case string:
		*e = WebhookSource(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookSource: %T", src)
	}
	return nil
}

type NullWebhookSource struct {
	WebhookSource WebhookSource `json:"webhook_source"`
	Valid         bool          `json:"valid"` // Valid is true if WebhookSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookSource) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookSource), nil
}

type AppRoleAccess struct {
	ApplicationID uuid.UUID `json:"application_id"`
	RoleID        uuid.UUID `json:"role_id"`
}

type AppSetting struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Application struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IconUrl     pgtype.Text `json:"icon_url"`
	AccessType  string      `json:"access_type"`
	TargetHost  string      `json:"target_host"`
	TargetPort  pgtype.Int4 `json:"target_port"`
	IsActive    bool        `json:"is_active"`
	IsPublic    bool        `json:"is_public"`
	SortOrder   int32       `json:"sort_order"`
	SectionID   pgtype.UUID `json:"section_id"`
	CreatedBy   pgtype.UUID `json:"created_by"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type AuditLog struct {
	ID            uuid.UUID   `json:"id"`
	ActorID       pgtype.UUID `json:"actor_id"`
	ActorUsername pgtype.Text `json:"actor_username"`
	Action        string      `json:"action"`
	ResourceType  pgtype.Text `json:"resource_type"`
	ResourceID    pgtype.Text `json:"resource_id"`
	Details       []byte      `json:"details"`
	IpAddress     pgtype.Text `json:"ip_address"`
	CreatedAt     time.Time   `json:"created_at"`
}

type CasbinRule struct {
	ID    int32       `json:"id"`
	Ptype pgtype.Text `json:"ptype"`
	V0    pgtype.Text `json:"v0"`
	V1    pgtype.Text `json:"v1"`
	V2    pgtype.Text `json:"v2"`
	V3    pgtype.Text `json:"v3"`
	V4    pgtype.Text `json:"v4"`
	V5    pgtype.Text `json:"v5"`
}

type CatalogSection struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
}

type CveFinding struct {
	ID               uuid.UUID   `json:"id"`
	ImageName        string      `json:"image_name"`
	ImageTag         string      `json:"image_tag"`
	CveID            string      `json:"cve_id"`
	Severity         string      `json:"severity"`
	PackageName      pgtype.Text `json:"package_name"`
	InstalledVersion pgtype.Text `json:"installed_version"`
	FixedVersion     pgtype.Text `json:"fixed_version"`
	Source           string      `json:"source"`
	ScanDate         time.Time   `json:"scan_date"`
	RawPayload       []byte      `json:"raw_payload"`
	CreatedAt        time.Time   `json:"created_at"`
}

type DeploymentReport struct {
	ID            uuid.UUID   `json:"id"`
	AppName       string      `json:"app_name"`
	ImageName     string      `json:"image_name"`
	ImageTag      string      `json:"image_tag"`
	TriggeredBy   pgtype.Text `json:"triggered_by"`
	Status        string      `json:"status"`
	CriticalCount int32       `json:"critical_count"`
	HighCount     int32       `json:"high_count"`
	MediumCount   int32       `json:"medium_count"`
	LowCount      int32       `json:"low_count"`
	ReportUrl     pgtype.Text `json:"report_url"`
	RawPayload    []byte      `json:"raw_payload"`
	PayloadHash   pgtype.Text `json:"payload_hash"`
	ReceivedAt    time.Time   `json:"received_at"`
}

type Notification struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	Title     string      `json:"title"`
	Body      string      `json:"body"`
	EventType string      `json:"event_type"`
	Severity  string      `json:"severity"`
	Read      bool        `json:"read"`
	LinkUrl   pgtype.Text `json:"link_url"`
	CreatedAt time.Time   `json:"created_at"`
}

type NotificationPreference struct {
	UserID    uuid.UUID `json:"user_id"`
	Channel   string    `json:"channel"`
	EventType string    `json:"event_type"`
	Enabled   bool      `json:"enabled"`
}

type OidcProvider struct {
	ID                uuid.UUID   `json:"id"`
	Name              string      `json:"name"`
	DisplayName       string      `json:"display_name"`
	IssuerUrl         string      `json:"issuer_url"`
	ClientID          string      `json:"client_id"`
	ClientSecret      string      `json:"client_secret"`
	Scopes            []string    `json:"scopes"`
	AutoProvision     bool        `json:"auto_provision"`
	DefaultRoleID     pgtype.UUID `json:"default_role_id"`
	IsActive          bool        `json:"is_active"`
	ClaimEmail        string      `json:"claim_email"`
	ClaimName         string      `json:"claim_name"`
	ClaimSubject      string      `json:"claim_subject"`
	ClaimGroups       string      `json:"claim_groups"`
	GroupRoleMappings []byte      `json:"group_role_mappings"`
	CreatedAt         time.Time   `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	TokenHash string      `json:"token_hash"`
	IssuedAt  time.Time   `json:"issued_at"`
	ExpiresAt time.Time   `json:"expires_at"`
	Revoked   bool        `json:"revoked"`
	UserAgent pgtype.Text `json:"user_agent"`
	IpAddress pgtype.Text `json:"ip_address"`
}

type Role struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CreatedAt   time.Time   `json:"created_at"`
}

type TeamsWebhookConfig struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	WebhookUrl string    `json:"webhook_url"`
	EventTypes []string  `json:"event_types"`
	IsActive   bool      `json:"is_active"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	DisplayName  pgtype.Text        `json:"display_name"`
	AuthType     string             `json:"auth_type"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	OidcProvider pgtype.Text        `json:"oidc_provider"`
	OidcSubject  pgtype.Text        `json:"oidc_subject"`
	OidcEmail    pgtype.Text        `json:"oidc_email"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type UserInvitation struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
	RoleIds     []uuid.UUID        `json:"role_ids"`
	TokenHash   string             `json:"token_hash"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	ExpiresAt   time.Time          `json:"expires_at"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

type WebhookEvent struct {
	ID             uuid.UUID          `json:"id"`
	Source         WebhookSource      `json:"source"`
	Status         WebhookEventStatus `json:"status"`
	Payload        []byte             `json:"payload"`
	PayloadPreview pgtype.Text        `json:"payload_preview"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	ReceivedAt     time.Time          `json:"received_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
}
