// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1 AND read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, title, body, event_type, severity, link_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, title, body, event_type, severity, read, link_url, created_at
`

type CreateNotificationParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	Title     string      `json:"title"`
	Body      string      `json:"body"`
	EventType string      `json:"event_type"`
	Severity  string      `json:"severity"`
	LinkUrl   pgtype.Text `json:"link_url"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.EventType,
		arg.Severity,
		arg.LinkUrl,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.EventType,
		&i.Severity,
		&i.Read,
		&i.LinkUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications WHERE created_at < $1
`

func (q *Queries) DeleteOldNotifications(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldNotifications, createdAt)
	return err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :many
SELECT user_id, channel, event_type, enabled FROM notification_preferences WHERE user_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID uuid.UUID) ([]NotificationPreference, error) {
	rows, err := q.db.Query(ctx, getNotificationPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationPreference{}
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(
			&i.UserID,
			&i.Channel,
			&i.EventType,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, user_id, title, body, event_type, severity, read, link_url, created_at FROM notifications WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListNotificationsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.EventType,
			&i.Severity,
			&i.Read,
			&i.LinkUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotificationsForUser = `-- name: ListUnreadNotificationsForUser :many
SELECT id, user_id, title, body, event_type, severity, read, link_url, created_at FROM notifications WHERE user_id = $1 AND read = FALSE ORDER BY created_at DESC LIMIT $2
`

type ListUnreadNotificationsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListUnreadNotificationsForUser(ctx context.Context, arg ListUnreadNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotificationsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.EventType,
			&i.Severity,
			&i.Read,
			&i.LinkUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read = TRUE WHERE user_id = $1 AND read = FALSE
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET read = TRUE WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const upsertNotificationPreference = `-- name: UpsertNotificationPreference :exec
INSERT INTO notification_preferences (user_id, channel, event_type, enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, channel, event_type) DO UPDATE SET enabled = EXCLUDED.enabled
`

type UpsertNotificationPreferenceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Channel   string    `json:"channel"`
	EventType string    `json:"event_type"`
	Enabled   bool      `json:"enabled"`
}

func (q *Queries) UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) error {
	_, err := q.db.Exec(ctx, upsertNotificationPreference,
		arg.UserID,
		arg.Channel,
		arg.EventType,
		arg.Enabled,
	)
	return err
}
