// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidc_providers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOIDCProvider = `-- name: CreateOIDCProvider :one
INSERT INTO oidc_providers (name, display_name, issuer_url, client_id, client_secret, scopes, auto_provision, default_role_id, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, display_name, issuer_url, client_id, client_secret, scopes, auto_provision, default_role_id, is_active, created_at
`

type CreateOIDCProviderParams struct {
	Name          string      `json:"name"`
	DisplayName   string      `json:"display_name"`
	IssuerUrl     string      `json:"issuer_url"`
	ClientID      string      `json:"client_id"`
	ClientSecret  string      `json:"client_secret"`
	Scopes        []string    `json:"scopes"`
	AutoProvision bool        `json:"auto_provision"`
	DefaultRoleID pgtype.UUID `json:"default_role_id"`
	IsActive      bool        `json:"is_active"`
}

func (q *Queries) CreateOIDCProvider(ctx context.Context, arg CreateOIDCProviderParams) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, createOIDCProvider,
		arg.Name,
		arg.DisplayName,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecret,
		arg.Scopes,
		arg.AutoProvision,
		arg.DefaultRoleID,
		arg.IsActive,
	)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.AutoProvision,
		&i.DefaultRoleID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOIDCProvider = `-- name: DeleteOIDCProvider :exec
DELETE FROM oidc_providers WHERE id = $1
`

func (q *Queries) DeleteOIDCProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOIDCProvider, id)
	return err
}

const getOIDCProviderByID = `-- name: GetOIDCProviderByID :one
SELECT id, name, display_name, issuer_url, client_id, client_secret, scopes, auto_provision, default_role_id, is_active, created_at FROM oidc_providers WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOIDCProviderByID(ctx context.Context, id uuid.UUID) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, getOIDCProviderByID, id)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.AutoProvision,
		&i.DefaultRoleID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getOIDCProviderByName = `-- name: GetOIDCProviderByName :one
SELECT id, name, display_name, issuer_url, client_id, client_secret, scopes, auto_provision, default_role_id, is_active, created_at FROM oidc_providers WHERE name = $1 LIMIT 1
`

func (q *Queries) GetOIDCProviderByName(ctx context.Context, name string) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, getOIDCProviderByName, name)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.AutoProvision,
		&i.DefaultRoleID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveOIDCProviders = `-- name: ListActiveOIDCProviders :many
SELECT id, name, display_name, issuer_url, client_id, scopes, auto_provision, default_role_id, is_active, created_at
FROM oidc_providers WHERE is_active = TRUE ORDER BY name
`

type ListActiveOIDCProvidersRow struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	DisplayName   string      `json:"display_name"`
	IssuerUrl     string      `json:"issuer_url"`
	ClientID      string      `json:"client_id"`
	Scopes        []string    `json:"scopes"`
	AutoProvision bool        `json:"auto_provision"`
	DefaultRoleID pgtype.UUID `json:"default_role_id"`
	IsActive      bool        `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) ListActiveOIDCProviders(ctx context.Context) ([]ListActiveOIDCProvidersRow, error) {
	rows, err := q.db.Query(ctx, listActiveOIDCProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveOIDCProvidersRow{}
	for rows.Next() {
		var i ListActiveOIDCProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.IssuerUrl,
			&i.ClientID,
			&i.Scopes,
			&i.AutoProvision,
			&i.DefaultRoleID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCProviders = `-- name: ListOIDCProviders :many
SELECT id, name, display_name, issuer_url, client_id, client_secret, scopes, auto_provision, default_role_id, is_active, created_at FROM oidc_providers ORDER BY name
`

func (q *Queries) ListOIDCProviders(ctx context.Context) ([]OidcProvider, error) {
	rows, err := q.db.Query(ctx, listOIDCProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OidcProvider{}
	for rows.Next() {
		var i OidcProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.IssuerUrl,
			&i.ClientID,
			&i.ClientSecret,
			&i.Scopes,
			&i.AutoProvision,
			&i.DefaultRoleID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOIDCProvider = `-- name: UpdateOIDCProvider :one
UPDATE oidc_providers SET
    display_name = $2, issuer_url = $3, client_id = $4, client_secret = $5,
    scopes = $6, auto_provision = $7, default_role_id = $8, is_active = $9
WHERE id = $1
RETURNING id, name, display_name, issuer_url, client_id, client_secret, scopes, auto_provision, default_role_id, is_active, created_at
`

type UpdateOIDCProviderParams struct {
	ID            uuid.UUID   `json:"id"`
	DisplayName   string      `json:"display_name"`
	IssuerUrl     string      `json:"issuer_url"`
	ClientID      string      `json:"client_id"`
	ClientSecret  string      `json:"client_secret"`
	Scopes        []string    `json:"scopes"`
	AutoProvision bool        `json:"auto_provision"`
	DefaultRoleID pgtype.UUID `json:"default_role_id"`
	IsActive      bool        `json:"is_active"`
}

func (q *Queries) UpdateOIDCProvider(ctx context.Context, arg UpdateOIDCProviderParams) (OidcProvider, error) {
	row := q.db.QueryRow(ctx, updateOIDCProvider,
		arg.ID,
		arg.DisplayName,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecret,
		arg.Scopes,
		arg.AutoProvision,
		arg.DefaultRoleID,
		arg.IsActive,
	)
	var i OidcProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.AutoProvision,
		&i.DefaultRoleID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
