// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setup.sql

package db

import (
	"context"
)

const hasAdminUser = `-- name: HasAdminUser :one
SELECT EXISTS (
    SELECT 1
    FROM user_roles ur
    JOIN roles r ON r.id = ur.role_id
    WHERE r.name = 'admin'
) AS has_admin
`

func (q *Queries) HasAdminUser(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasAdminUser)
	var has_admin bool
	err := row.Scan(&has_admin)
	return has_admin, err
}
