// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams_webhooks.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTeamsWebhookConfig = `-- name: CreateTeamsWebhookConfig :one
INSERT INTO teams_webhook_configs (name, webhook_url, event_types, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, name, webhook_url, event_types, is_active, created_at
`

type CreateTeamsWebhookConfigParams struct {
	Name       string   `json:"name"`
	WebhookUrl string   `json:"webhook_url"`
	EventTypes []string `json:"event_types"`
	IsActive   bool     `json:"is_active"`
}

func (q *Queries) CreateTeamsWebhookConfig(ctx context.Context, arg CreateTeamsWebhookConfigParams) (TeamsWebhookConfig, error) {
	row := q.db.QueryRow(ctx, createTeamsWebhookConfig,
		arg.Name,
		arg.WebhookUrl,
		arg.EventTypes,
		arg.IsActive,
	)
	var i TeamsWebhookConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WebhookUrl,
		&i.EventTypes,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTeamsWebhookConfig = `-- name: DeleteTeamsWebhookConfig :exec
DELETE FROM teams_webhook_configs WHERE id = $1
`

func (q *Queries) DeleteTeamsWebhookConfig(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeamsWebhookConfig, id)
	return err
}

const getTeamsWebhookConfigByID = `-- name: GetTeamsWebhookConfigByID :one
SELECT id, name, webhook_url, event_types, is_active, created_at FROM teams_webhook_configs WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTeamsWebhookConfigByID(ctx context.Context, id uuid.UUID) (TeamsWebhookConfig, error) {
	row := q.db.QueryRow(ctx, getTeamsWebhookConfigByID, id)
	var i TeamsWebhookConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WebhookUrl,
		&i.EventTypes,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveTeamsWebhookConfigs = `-- name: ListActiveTeamsWebhookConfigs :many
SELECT id, name, webhook_url, event_types, is_active, created_at FROM teams_webhook_configs WHERE is_active = TRUE
`

func (q *Queries) ListActiveTeamsWebhookConfigs(ctx context.Context) ([]TeamsWebhookConfig, error) {
	rows, err := q.db.Query(ctx, listActiveTeamsWebhookConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamsWebhookConfig{}
	for rows.Next() {
		var i TeamsWebhookConfig
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WebhookUrl,
			&i.EventTypes,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsWebhookConfigs = `-- name: ListTeamsWebhookConfigs :many
SELECT id, name, webhook_url, event_types, is_active, created_at FROM teams_webhook_configs ORDER BY name
`

func (q *Queries) ListTeamsWebhookConfigs(ctx context.Context) ([]TeamsWebhookConfig, error) {
	rows, err := q.db.Query(ctx, listTeamsWebhookConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamsWebhookConfig{}
	for rows.Next() {
		var i TeamsWebhookConfig
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WebhookUrl,
			&i.EventTypes,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeamsWebhookConfig = `-- name: UpdateTeamsWebhookConfig :one
UPDATE teams_webhook_configs SET name = $2, webhook_url = $3, event_types = $4, is_active = $5
WHERE id = $1
RETURNING id, name, webhook_url, event_types, is_active, created_at
`

type UpdateTeamsWebhookConfigParams struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	WebhookUrl string    `json:"webhook_url"`
	EventTypes []string  `json:"event_types"`
	IsActive   bool      `json:"is_active"`
}

func (q *Queries) UpdateTeamsWebhookConfig(ctx context.Context, arg UpdateTeamsWebhookConfigParams) (TeamsWebhookConfig, error) {
	row := q.db.QueryRow(ctx, updateTeamsWebhookConfig,
		arg.ID,
		arg.Name,
		arg.WebhookUrl,
		arg.EventTypes,
		arg.IsActive,
	)
	var i TeamsWebhookConfig
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WebhookUrl,
		&i.EventTypes,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
