// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO user_roles (user_id, role_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserRoleParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.Exec(ctx, addUserRole, arg.UserID, arg.RoleID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, display_name, auth_type, password_hash, oidc_provider, oidc_subject, oidc_email)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, username, email, display_name, auth_type, password_hash, oidc_provider, oidc_subject, oidc_email, last_login_at, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	DisplayName  pgtype.Text `json:"display_name"`
	AuthType     string      `json:"auth_type"`
	PasswordHash pgtype.Text `json:"password_hash"`
	OidcProvider pgtype.Text `json:"oidc_provider"`
	OidcSubject  pgtype.Text `json:"oidc_subject"`
	OidcEmail    pgtype.Text `json:"oidc_email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.AuthType,
		arg.PasswordHash,
		arg.OidcProvider,
		arg.OidcSubject,
		arg.OidcEmail,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AuthType,
		&i.PasswordHash,
		&i.OidcProvider,
		&i.OidcSubject,
		&i.OidcEmail,
		&i.LastLoginAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, display_name, auth_type, password_hash, oidc_provider, oidc_subject, oidc_email, last_login_at, is_active, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AuthType,
		&i.PasswordHash,
		&i.OidcProvider,
		&i.OidcSubject,
		&i.OidcEmail,
		&i.LastLoginAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, display_name, auth_type, password_hash, oidc_provider, oidc_subject, oidc_email, last_login_at, is_active, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AuthType,
		&i.PasswordHash,
		&i.OidcProvider,
		&i.OidcSubject,
		&i.OidcEmail,
		&i.LastLoginAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOIDC = `-- name: GetUserByOIDC :one
SELECT id, username, email, display_name, auth_type, password_hash, oidc_provider, oidc_subject, oidc_email, last_login_at, is_active, created_at, updated_at FROM users WHERE oidc_provider = $1 AND oidc_subject = $2 LIMIT 1
`

type GetUserByOIDCParams struct {
	OidcProvider pgtype.Text `json:"oidc_provider"`
	OidcSubject  pgtype.Text `json:"oidc_subject"`
}

func (q *Queries) GetUserByOIDC(ctx context.Context, arg GetUserByOIDCParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOIDC, arg.OidcProvider, arg.OidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AuthType,
		&i.PasswordHash,
		&i.OidcProvider,
		&i.OidcSubject,
		&i.OidcEmail,
		&i.LastLoginAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, display_name, auth_type, password_hash, oidc_provider, oidc_subject, oidc_email, last_login_at, is_active, created_at, updated_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AuthType,
		&i.PasswordHash,
		&i.OidcProvider,
		&i.OidcSubject,
		&i.OidcEmail,
		&i.LastLoginAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.name, r.description, r.created_at FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByRoleName = `-- name: GetUsersByRoleName :many
SELECT u.id, u.username, u.email, u.display_name, u.auth_type, u.password_hash, u.oidc_provider, u.oidc_subject, u.oidc_email, u.last_login_at, u.is_active, u.created_at, u.updated_at FROM users u
JOIN user_roles ur ON ur.user_id = u.id
JOIN roles r ON r.id = ur.role_id
WHERE r.name = $1 AND u.is_active = TRUE
`

func (q *Queries) GetUsersByRoleName(ctx context.Context, name string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByRoleName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.AuthType,
			&i.PasswordHash,
			&i.OidcProvider,
			&i.OidcSubject,
			&i.OidcEmail,
			&i.LastLoginAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByRoleNames = `-- name: GetUsersByRoleNames :many
SELECT DISTINCT u.id, u.username, u.email, u.display_name, u.auth_type, u.password_hash, u.oidc_provider, u.oidc_subject, u.oidc_email, u.last_login_at, u.is_active, u.created_at, u.updated_at FROM users u
JOIN user_roles ur ON ur.user_id = u.id
JOIN roles r ON r.id = ur.role_id
WHERE r.name = ANY($1::text[]) AND u.is_active = TRUE
ORDER BY u.email
`

func (q *Queries) GetUsersByRoleNames(ctx context.Context, dollar_1 []string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByRoleNames, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.AuthType,
			&i.PasswordHash,
			&i.OidcProvider,
			&i.OidcSubject,
			&i.OidcEmail,
			&i.LastLoginAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, display_name, auth_type, password_hash, oidc_provider, oidc_subject, oidc_email, last_login_at, is_active, created_at, updated_at FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.AuthType,
			&i.PasswordHash,
			&i.OidcProvider,
			&i.OidcSubject,
			&i.OidcEmail,
			&i.LastLoginAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserRoles = `-- name: SetUserRoles :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) SetUserRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setUserRoles, userID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    email = COALESCE($2, email),
    display_name = COALESCE($3, display_name),
    auth_type = COALESCE($4, auth_type),
    password_hash = COALESCE($5, password_hash),
    oidc_provider = COALESCE($6, oidc_provider),
    oidc_subject = COALESCE($7, oidc_subject),
    oidc_email = COALESCE($8, oidc_email),
    is_active = COALESCE($9, is_active),
    last_login_at = COALESCE($10, last_login_at),
    updated_at = now()
WHERE id = $1
RETURNING id, username, email, display_name, auth_type, password_hash, oidc_provider, oidc_subject, oidc_email, last_login_at, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	ID           uuid.UUID          `json:"id"`
	Email        pgtype.Text        `json:"email"`
	DisplayName  pgtype.Text        `json:"display_name"`
	AuthType     NullAuthType       `json:"auth_type"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	OidcProvider pgtype.Text        `json:"oidc_provider"`
	OidcSubject  pgtype.Text        `json:"oidc_subject"`
	OidcEmail    pgtype.Text        `json:"oidc_email"`
	IsActive     pgtype.Bool        `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.AuthType,
		arg.PasswordHash,
		arg.OidcProvider,
		arg.OidcSubject,
		arg.OidcEmail,
		arg.IsActive,
		arg.LastLoginAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AuthType,
		&i.PasswordHash,
		&i.OidcProvider,
		&i.OidcSubject,
		&i.OidcEmail,
		&i.LastLoginAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}
