// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWebhookEvents = `-- name: CountWebhookEvents :one
SELECT COUNT(*) FROM webhook_events
WHERE ($1 = '' OR source::text = $1)
`

func (q *Queries) CountWebhookEvents(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookEvents, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhookEvent = `-- name: CreateWebhookEvent :one
INSERT INTO webhook_events (source, status, payload, payload_preview)
VALUES ($1, 'accepted', $2, $3)
RETURNING id, source, status, payload, payload_preview, error_message, received_at, processed_at
`

type CreateWebhookEventParams struct {
	Source         WebhookSource `json:"source"`
	Payload        []byte        `json:"payload"`
	PayloadPreview pgtype.Text   `json:"payload_preview"`
}

func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, createWebhookEvent, arg.Source, arg.Payload, arg.PayloadPreview)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Status,
		&i.Payload,
		&i.PayloadPreview,
		&i.ErrorMessage,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const deleteOldWebhookEvents = `-- name: DeleteOldWebhookEvents :exec
DELETE FROM webhook_events WHERE received_at < $1
`

func (q *Queries) DeleteOldWebhookEvents(ctx context.Context, receivedAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldWebhookEvents, receivedAt)
	return err
}

const getWebhookEventByID = `-- name: GetWebhookEventByID :one
SELECT id, source, status, payload, payload_preview, error_message, received_at, processed_at FROM webhook_events WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWebhookEventByID(ctx context.Context, id uuid.UUID) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEventByID, id)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Status,
		&i.Payload,
		&i.PayloadPreview,
		&i.ErrorMessage,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const listWebhookEvents = `-- name: ListWebhookEvents :many
SELECT id, source, status, payload, payload_preview, error_message, received_at, processed_at FROM webhook_events
WHERE ($1 = '' OR source::text = $1)
ORDER BY received_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookEventsParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListWebhookEvents(ctx context.Context, arg ListWebhookEventsParams) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listWebhookEvents, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Status,
			&i.Payload,
			&i.PayloadPreview,
			&i.ErrorMessage,
			&i.ReceivedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookEventStatus = `-- name: UpdateWebhookEventStatus :exec
UPDATE webhook_events
SET status = $2, error_message = $3, processed_at = now()
WHERE id = $1
`

type UpdateWebhookEventStatusParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       WebhookEventStatus `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
}

func (q *Queries) UpdateWebhookEventStatus(ctx context.Context, arg UpdateWebhookEventStatusParams) error {
	_, err := q.db.Exec(ctx, updateWebhookEventStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
